version: "3"
services:
  postgres:
    image: "postgres:11-alpine"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: project_dev
    ports:
    - "5432:5432"
